### ISSUE TITLE
A possible code error

### ISSUE THREAD

**Issue by ghost** [popura/itmnet_pytorch#1]
in the itmnet-pytorch/src/itmnet.py, line 35
Is the kernel_size=(2,2) or kernel_size=(3,3)?

Your paper has said "Max pool which downsamples feature maps by max pooling with a kernel size of 2 x 2 and a stride of 2"

**Comment by popura** [comment]
They are not errors.
In this implementation, original max pooling layers are replaced with strided convolutional layers having a kernel size of 3 x 3.
